### PR TITLE
Misc Updates, Cleanup After Decaf

### PR DESCRIPTION
**Pull request by confused-Techie**
EDIT:

Since the diff here was quite large I've change the base to our `decaf` branch. This means this review only has to consider the actually changes for this PR. Rather than the changes that are present from our `decaf` branch to the main branch.

Hopefully these changes will make this PR easier to review.

---

This PR had a few accomplishments.

Originally I had hoped to include the removal of `oniguruma` since I was optimistic that [`bcoe/onigurumajs`](https://github.com/bcoe/onigurumajs) would be a drop in replacement. Unfortunately it is not. I also checked to see if the modifications can be low and use [`tenbits/oniguruma-js`](https://github.com/tenbits/oniguruma-js) or even use [`vscode-oniguruma`](https://github.com/microsoft/vscode-oniguruma/).

But it seems that from the majority of these JavaScript implementations were created before an important API change in `node-oniguruma`, namely introducing `OnigString` on PR [#46](https://github.com/atom/node-oniguruma/pull/46).

Most of these forks don't actually include this functionality, meaning it's not a direct translation anymore. I did attempt at reverting the changes in First-Mate to use this new feature, which I beleive are all contained on [this commit](https://github.com/atom/first-mate/commit/7c1650462e834bf0ecaa224e3bddb9e67d1a8629), but alas still we had tests failing. 

So work will need to continue on removing this native module.

---

But otherwise for other changes there are plenty here, I've rebranded the links in the `package.json`, additionally decaffed our `Gruntfile.coffee` and gutted the majority of it's functionality. Really leaving it to be a task to generate our docs for `grunt-atomdoc` (Which quick note on that. Now fails because it seems to not understand how to find our docs once we have decaffed. But fixing that is far out of scope for this PR), additionally I've removed all other deps that we no longer need since we have moved away from using grunt for everything.

I did add a new script to run `PegJS` rather than let grunt do it.

Really the reasoning behind this was because this repo has stayed static for some time, and we have moved mostly away from using First-Mate as the recommended syntax highlighter, I highly doubt we will need to change PegJS code all that much.

So in the unexpected event that we do, all we have to do is run `npm run parse` and it'll be parsed for us.
With that change in mind I did add this to the ReadMe Documentation, to ensure everyone is aware of this change.

Also speaking of PegJS, I've updated PegJS to the latest version, and ran the parsing again. Still all tests pass, but the diff on `scope-selector-parser.js` is huge because of this. I would not recommend reviewing this manually as this was an automated change, that has no effect on our tests passing.

But besides a few other dep bumps, that's all thats contained in this PR. The diff is large and I apologize, but that's because I'm targeting all the approved decaf changes to our master branch now. Meaning those are showing up in this review as well. I'd personally recommend looking at the commits themselves, and everything after 56b7f8f27cdfc6ed542058867c9f45dc9cfe19de is what has actually been changed on this PR.

Thanks to anyone that is able to review!

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Sorry for not noticing this right away. For ease of review this PR can target the decaf branch, and then for ease of merging to `master` you can switch the target branch to `master` at the last minute?

(And if this gets merged to the decaf branch a final merge of the decaf branch over to `master` would also be pretty clean.)

_THAT SAID_ I will probably not be doing much review of this JS, unless no-one else does and if the diff is small enough and obvious what it is about. I'll note that tests are passing, so that's a pretty good sign.

**Comment by confused-Techie** [comment]
> Sorry for not noticing this right away. For ease of review this PR can target the decaf branch, and then for ease of merging to `master` you can switch the target branch to `master` at the last minute?
> 
> (And if this gets merged to the decaf branch a final merge of the decaf branch over to `master` would also be pretty clean.)
> 
> _THAT SAID_ I will probably not be doing much review of this JS, unless no-one else does and if the diff is small enough and obvious what it is about. I'll note that tests are passing, so that's a pretty good sign.

Good call. I've gone ahead and targeted the `decaf` branch for this PR. Once this is approved I will create another PR from decaf to main. But otherwise thanks for taking a look at this.

**Comment by confused-Techie** [comment]
Bumping this PR. While generally we don't like to merge code changes that are not fully reviewed, I'm hoping to get this merged prior to seeing if we can move this into the core editor.

Again all tests are passing here, so anyone that wants to take a look feel free to do so.

**Review by mauricioszabo — APPROVED** [review]

**Comment by confused-Techie** [comment]
Thanks for the approval @mauricioszabo I'll get this one merged!

**Pull request merged**
